name: Build

on:
  workflow_dispatch:

jobs:
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker meta names
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: convictional/trigger-workflow-and-wait
        tags: |
          type=ref,event=tag
          type=raw,enable=${{ !startsWith(github.ref, 'refs/tags/') }},value=master
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        context: .

  self-test:
    name: Run self-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
            owner: robinatwork1999
            repo: product-commerce
            github_token: ${{ secrets.TOKEN }}
            workflow_file_name: cc.yml
            client_payload: '{"emailid": "11111"}'
            wait_workflow: true  
