name: Build

on:
  workflow_dispatch:

jobs:
  self-test:
    name: Run self-test
    runs-on: ubuntu-latest
    steps:
      - uses: robinatwork1999/trigeerwf@main
        with:
            owner: robinatwork1999
            repo: product-commerce
            github_token: ${{ secrets.TOKEN }}
            workflow_file_name: cc.yml
            client_payload: '{"emailid": "11111"}'
            wait_workflow: true  
